server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev.bc.office.ysb:3306/cd_database?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: AAbb11@@
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.yunshaoboedu.bmp.entity
  configuration:
    map-underscore-to-camel-case: true
